# Used to create the local cluster. 
# Create with `kind create cluster --config ./kind-cluster.yaml`
# Not directly created with Terraform.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 30000
      hostPort: 30000
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp
    extraMounts:
    - hostPath: /home/jered/workplace/team-engineering/airflow/dags
      containerPath: /mnt/airflow/dags