argocd_version = "5.16.13"
domain_name = "test.org"
sealed_secrets_tls_key_path = "~/.sealed-secrets/certs/mytls.key"
sealed_secrets_tls_cert_path = "~/.sealed-secrets/certs/mytls.crt"
sealed_secrets_secret_id = "sealed-secrets-tls"
metric_server_revision = "3.8.3"