apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-master-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.githubRepo }}
    targetRevision: HEAD
    path: argo-master-apps
    directory:
      recurse: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: argo-master-apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true